# Scheduler settings
ncpus: 1000
walltime: 2:00:00
runspersub: 50
jobname: la2_t1e-1
project: g40
queue: express
qsub_flags: -lother=hyperthread -W umask=027 -lstorage=gdata/v45+scratch/v45+gdata/hh5

# for normal
platform:
    nodesize: 48

# Model settings
model: mom6
shortpath: /scratch/v45
exe: MOM6-25Jan2020 
input: henk-realistic-layer2_tau1p0e-01


# Postprocessing
collate: False
#userscripts:
#    archive: sync_output_to_gdata.sh

