format: yamanifest
version: 1.0
---
work/INPUT/domain.pdf:
  fullpath: /scratch/v45/nc3020/mom6/input/henk-realistic-layer2_tau1p0e-01/domain.pdf
  hashes:
    binhash: 3576423f799868176dabfd6df1b9d936
    md5: 593dbc295b2b6f706a986724d1a159e3
work/INPUT/driver-layers-topo-densities.nc:
  fullpath: /scratch/v45/nc3020/mom6/input/henk-realistic-layer2_tau1p0e-01/driver-layers-topo-densities.nc
  hashes:
    binhash: 6c457296cbcb318b3c26b2365ca5f101
    md5: 38d72e9374d2910782de5ef9c41d9a54
work/INPUT/windstress.nc:
  fullpath: /scratch/v45/nc3020/mom6/input/henk-realistic-layer2_tau1p0e-01/windstress.nc
  hashes:
    binhash: 873aabe361879d0657b81aac0d79e11f
    md5: 5ca7408b17a704d312ecca2199f3922c
work/INPUT/windstress.pdf:
  fullpath: /scratch/v45/nc3020/mom6/input/henk-realistic-layer2_tau1p0e-01/windstress.pdf
  hashes:
    binhash: 05d711754fb893f9297a5b35d1f8f1b6
    md5: b604d30d21810948da55a3e2c0bf7c7a
